package store

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

// TagList is a set of tag names stored in a single TEXT column as a JSON array.
// Tags deliberately live on the entry row rather than in a table of their own: sync
// resolves last-write-wins per row, so a tag edit has to be the same single row write
// as editing a description, and a fourth synced table would break the sequence
// allocation in Sync, which reserves a block sized by hand from three slices.
type TagList []string

// Value encodes the list for SQLite. An empty list is stored as "[]" rather than
// NULL so the column can stay NOT NULL for rows written before the tags migration.
func (list TagList) Value() (driver.Value, error) {
	if len(list) == 0 {
		return "[]", nil
	}
	encoded, err := json.Marshal([]string(list))
	if err != nil {
		return nil, err
	}
	return string(encoded), nil
}

// Scan decodes the column. NULL and an empty string both yield an empty, non-nil
// list, so a scanned entry always marshals its tags as [] and never as null.
func (list *TagList) Scan(value any) error {
	*list = TagList{}
	var raw []byte
	switch typed := value.(type) {
	case nil:
		return nil
	case string:
		raw = []byte(typed)
	case []byte:
		raw = typed
	default:
		return fmt.Errorf("tags: cannot scan %T", value)
	}
	if len(raw) == 0 {
		return nil
	}
	decoded := []string{}
	if err := json.Unmarshal(raw, &decoded); err != nil {
		return fmt.Errorf("tags: %w", err)
	}
	*list = decoded
	return nil
}

// MarshalJSON keeps a nil list on the wire as [] so clients never have to treat
// null and "no tags" as separate cases.
func (list TagList) MarshalJSON() ([]byte, error) {
	if list == nil {
		return []byte("[]"), nil
	}
	return json.Marshal([]string(list))
}

type User struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	Name       string `json:"name"`
	PictureURL string `json:"picture_url"`
}

type Project struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Color     string `json:"color"`
	Archived  bool   `json:"archived"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
	DeletedAt *int64 `json:"deleted_at"`
	ServerSeq int64  `json:"server_seq,omitempty"`
}

type TimeEntry struct {
	ID          string  `json:"id"`
	ProjectID   *string `json:"project_id"`
	Description string  `json:"description"`
	Tags        TagList `json:"tags"`
	StartedAt   int64   `json:"started_at"`
	StoppedAt   *int64  `json:"stopped_at"`
	CreatedAt   int64   `json:"created_at"`
	UpdatedAt   int64   `json:"updated_at"`
	DeletedAt   *int64  `json:"deleted_at"`
	ServerSeq   int64   `json:"server_seq,omitempty"`
	// AgentSessionID is server-owned; push never changes it. Clients read it to
	// label a row with the agent session that produced it. Ids are generated by
	// the client, so a pushed value would let anyone claim someone else's session.
	AgentSessionID *string `json:"agent_session_id"`
}

type TimeOff struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	DateFrom  string `json:"date_from"`
	DateTo    string `json:"date_to"`
	Note      string `json:"note"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
	DeletedAt *int64 `json:"deleted_at"`
	ServerSeq int64  `json:"server_seq,omitempty"`
}

type SyncChanges struct {
	Projects    []Project   `json:"projects,omitempty"`
	TimeEntries []TimeEntry `json:"time_entries,omitempty"`
	TimeOff     []TimeOff   `json:"time_off,omitempty"`
}

type SyncRequest struct {
	Since   int64       `json:"since"`
	Changes SyncChanges `json:"changes"`
}

type SyncResponse struct {
	Seq     int64       `json:"seq"`
	Changes SyncChanges `json:"changes"`
}

type ProjectReport struct {
	ProjectID *string `json:"project_id"`
	TotalMs   int64   `json:"total_ms"`
}

type TimeOffReport struct {
	Kind string `json:"kind"`
	Days int    `json:"days"`
}

type Report struct {
	Projects []ProjectReport `json:"projects"`
	TimeOff  []TimeOffReport `json:"time_off"`
}
